import { ToolType } from "./model";

export const standardTools: { [key in ToolType]: string[] } = {
  "Artisans Tools": [
    "Alchemist's Supplies",
    "Brewer's Supplies",
    "Calligrapher's Supplies",
    "Carpenter's Tools",
    "Cartographer's Tools",
    "Cobbler's Tools",
    "Cook's Utensils",
    "Glassblower's Tools",
    "Jeweler's Tools",
    "Leatherworker's Tools",
    "Mason's Tools",
    "Painter's Supplies",
    "Potter's Tools",
    "Smith's Tools",
    "Tinker's Tools",
    "Weaver's Tools",
    "Woodcarver's Tools",
    "Disguise Kit",
    "Forgery Kit",
    "Herbalism Kit",
    "Navigator's Tools",
    "Poisoner's Kit",
    "Thieves' Tools",
  ],
  Instruments: [
    "Bagpipes",
    "Drum",
    "Dulcimer",
    "Flute",
    "Lute",
    "Horn",
    "Pan Flute",
    "Shawm",
    "Lyre",
    "Viol",
    "Birdpipes",
    "Glaur",
    "Hand Drum",
    "Longhorn",
    "Songhorn",
    "Tantan",
    "Thelarr",
    "Tocken",
    "Wargong",
    "Yarting",
    "Zulkoon",
    "Whistle-Stick",
  ],
  "Playing Sets": [
    "Dice Set",
    "Playing Card Set",
    "Three-Dragon Ante Set",
    "Dragonchess Set",
  ],
  Vehicles: ["Land Vehicle", "Water Vehicle"],
};
